---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '15 3 * * 1'
jobs:
  php-lint:
    name: "PHP linter"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2
      - name: "Run PHP lint"
        run: "composer ci:php:lint"
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 7.4
          - 8.0
  code-quality:
    name: "Code quality checks"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2
      - name: "Show Composer version"
        run: composer --version
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          key: "php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php${{ matrix.php-version }}-composer-\n"
      - name: "Install Composer dependencies"
        run: "composer install --no-progress"
      - name: "Run command"
        run: "composer ci:${{ matrix.command }}"
    strategy:
      fail-fast: false
      matrix:
        command:
          - "test"
        php-version:
          - 7.4
          - 8.0
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        versions:
          - { typo3: 11, testing: 6, php: 7.4 }
          - { typo3: 11, testing: 6, php: 8.0 }
    name: "Run tests with PHP ${{ matrix.versions.php }}
          using TYPO3 ${{ matrix.versions.typo3 }}
          with testing framework version ${{ matrix.versions.testing }}"
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.versions.php }}
          extensions: intl, mbstring, pdo_sqlite

      - name: "Cache composer dependencies"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.versions.php }}
            -typo3-${{ matrix.versions.typo3 }}
            -testing-${{ matrix.versions.testing }}
            -composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php-${{ matrix.versions.php }}
            -typo3-${{ matrix.versions.typo3 }}
            -testing-${{ matrix.versions.testing }}composer-
            php-${{ matrix.versions.php }}-typo3-
      - name: "Install composer dependencies"
        run: composer require typo3/minimal
          "^${{ matrix.versions.typo3 }}"
          typo3/testing-framework "^${{ matrix.versions.testing }}"
          --prefer-dist --no-progress --no-suggest

      #      - name: "Run Unit tests"
      #        run: composer ci:test:unit

      - name: "Functional tests"
        run: composer ci:test:functional
